=== EvaSky/EpamJavaTraining/Task_2.1_3.1/src/by/epam/xmlparsers/resources/menu.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.tc.com/menu"
        xmlns:tns="http://www.epam.tc.com/menu">

    <element name="menu">
        <complexType>
            <sequence>
                <element name="section" type="tns:Section" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Section">
        <sequence>
            <element name="section-name">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Холодные закуски"/>
                        <enumeration value="Горячие закуски"/>
                        <enumeration value="Завтраки"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="dishes" type="tns:Dishes"/>
        </sequence>
    </complexType>

    <complexType name="Dishes">
        <sequence>
            <element name="dish" maxOccurs="unbounded">
                <complexType>
                    <group ref="tns:DishDescription"/>
                    <attribute name="id" type="ID"/>
                </complexType>
            </element>
        </sequence>
    </complexType>

    <group name="DishDescription">
        <sequence>
            <element name="photo" type="string" minOccurs="0"/>
            <element name="name" type="string"/>
            <element name="description" type="string" minOccurs="0"/>
            <element name="helping-weight" type="string"/>
            <element name="price" type="string" minOccurs="0"/>
        </sequence>
    </group>

</schema>

=== EvaSky/EpamJavaTraining/Task_2.2/src/by/epam/parser/resources/menu.xml
<?xml version="1.0" encoding="utf-8"?>
<tc:menu
            xmlns:tc="http://www.epam.tc.com/menu"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.epam.tc.com/menu menu.xsd">

    <section>
        <section-name>Холодные закуски</section-name>
        <dishes>
            <dish id="d1.1">
                <photo>11.jpg</photo>
                <name>Ассорти рыбное</name>
                <description>Слабосоленая форель, семга</description>
                <helping-weight>100/20/15</helping-weight>
            </dish>
            <dish id="d1.2">
                <photo>12.jpg</photo>
                <name>Куриный рулет</name>
                <description>Куриный рулет собственного производства</description>
                <helping-weight>100/5</helping-weight>
            </dish>
            <dish id="d1.3">
                <photo>13.jpg</photo>
                <name>Овощной букет</name>
                <description>Корейская морковь, капуста, фунчоза</description>
                <helping-weight>150/10</helping-weight>
            </dish>
        </dishes>
    </section>

    <section>
        <section-name>Горячие закуски</section-name>
        <dishes>
            <dish id="d2.1">
                <photo>21.jpg</photo>
                <name>Лобио с шампиньонами</name>
                <description>Фасоль с шампиньонами и грецким орехом</description>
                <helping-weight>150.5</helping-weight>
                <price>105</price>
            </dish>
            <dish id="d2.2">
                <photo>22.jpg</photo>
                <name>Жульен</name>
                <description>1. с курицей 2. с грибами</description>
                <helping-weight>120.1</helping-weight>
                <price>1.145 2.155</price>
            </dish >
            <dish id="d2.3">
                <photo>23.jpg</photo>
                <name>Сюрприз</name>
                <helping-weight>1 шт.</helping-weight>
                <price>260</price>
            </dish>
        </dishes>
    </section>

    <section>
        <section-name>Завтраки</section-name>
        <dishes>
            <dish id="d3.1">
                <photo>31jpg</photo>
                <name>Глазунья</name>
                <description>2 яйца (на выбор: ветчина, сыр, помидоры)</description>
                <helping-weight>150</helping-weight>
            </dish>
            <dish id="d3.2">
                <photo>32.jpg</photo>
                <name>Омлет</name>
                <helping-weight>100</helping-weight>
            </dish>
            <dish id="d3.3">
                <photo>33.jpg</photo>
                <name>Блинчики с мясом</name>
                <description>Жареные блинчики с мясом</description>
                <helping-weight>150</helping-weight>
            </dish>
        </dishes>
    </section>
</tc:menu>
